# Generated by Django 3.0.7 on 2020-06-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0003_match_date'),
        ('fixtures_points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='logo_uri',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='state',
        ),
        migrations.AddField(
            model_name='fixture',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('winner_point', models.IntegerField()),
                ('loser_point', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='manage_matches.Match')),
                ('point_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_team_1', to='manage_matches.Match')),
                ('point_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_team_2', to='manage_matches.Match')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_team_winner', to='manage_matches.Match')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='fixtures_points.Group'),
        ),
    ]
