# Generated by Django 3.0.7 on 2020-06-13 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_teams', '0001_initial'),
        ('fixtures_points', '0002_auto_20200613_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='point',
            name='point_team_1',
        ),
        migrations.RemoveField(
            model_name='point',
            name='point_team_2',
        ),
        migrations.RemoveField(
            model_name='point',
            name='winner',
        ),
        migrations.AddField(
            model_name='fixture',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_team_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_team_1', to='manage_teams.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='fixture_team_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_team_2', to='manage_teams.Team'),
        ),
    ]
