# Generated by Django 3.0.7 on 2020-06-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_teams', '0001_initial'),
        ('fixtures_points', '0003_auto_20200613_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='fixture_team_1',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='fixture_team_2',
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='manage_teams.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='manage_teams.Team'),
        ),
    ]
