# Generated by Django 3.0.7 on 2020-06-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures_points', '0004_auto_20200613_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
