# Generated by Django 3.0.7 on 2020-06-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_teams', '0001_initial'),
        ('fixtures_points', '0006_auto_20200613_2234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together={('team1', 'team2')},
        ),
    ]
