# Generated by Django 3.0.7 on 2020-06-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures_points', '0007_auto_20200614_0006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixture',
            unique_together=set(),
        ),
    ]
