# Generated by Django 3.0.7 on 2020-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image_uri', models.ImageField(upload_to='')),
                ('jersey_number', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
