# Generated by Django 3.0.7 on 2020-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_players', '0003_auto_20200613_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image_uri',
            field=models.CharField(max_length=255),
        ),
    ]
