# Generated by Django 3.0.7 on 2020-06-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_teams', '0001_initial'),
        ('manage_players', '0006_auto_20200613_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_teams.Team'),
        ),
    ]
