# Generated by Django 3.0.7 on 2020-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('team1', models.CharField(max_length=255)),
                ('team2', models.CharField(max_length=255)),
                ('winner', models.ImageField(upload_to='media')),
                ('team1_score', models.IntegerField()),
                ('team2_score', models.IntegerField()),
            ],
        ),
    ]
