# Generated by Django 3.0.7 on 2020-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0002_auto_20200613_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
