# Generated by Django 3.0.7 on 2020-06-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures_points', '0005_delete_point'),
        ('manage_matches', '0004_auto_20200613_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='fixture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures_points.Fixture'),
        ),
    ]
