# Generated by Django 3.0.7 on 2020-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0006_auto_20200613_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='match_suspended',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='point',
            name='loser_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='point',
            name='winner_point',
            field=models.IntegerField(default=3),
        ),
    ]
