# Generated by Django 3.0.7 on 2020-06-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0007_auto_20200613_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='match_suspended',
        ),
    ]
