# Generated by Django 3.0.7 on 2020-06-14 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0009_remove_match_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_matches.Point'),
        ),
    ]
