# Generated by Django 3.0.7 on 2020-06-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0010_match_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='point',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
