# Generated by Django 3.0.7 on 2020-06-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_teams', '0001_initial'),
        ('manage_matches', '0011_auto_20200614_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('winner_point', models.IntegerField(default=3)),
                ('loser_point', models.IntegerField(default=0)),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='manage_teams.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_matches.Point'),
        ),
    ]
