# Generated by Django 3.0.7 on 2020-06-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0012_auto_20200614_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='fixture',
        ),
    ]
