# Generated by Django 3.0.7 on 2020-06-14 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures_points', '0008_auto_20200614_0012'),
        ('manage_matches', '0013_remove_match_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fixture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures_points.Fixture'),
        ),
    ]
