# Generated by Django 3.0.7 on 2020-06-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0014_match_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='winner',
        ),
    ]
