# Generated by Django 3.0.7 on 2020-06-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_matches', '0016_auto_20200614_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='match_suspended',
        ),
    ]
