# Generated by Django 3.0.7 on 2020-06-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_uri', models.ImageField(upload_to='media')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
